export const initialConfig = {
  seats: [
    [
      { row: 1, seat: 1 },
      { row: 1, seat: 2 },
      { row: 1, seat: 3 },
      { row: 1, seat: 4 },
      { row: 1 },
      { row: 1 },
      { row: 1, seat: 5 },
      { row: 1, seat: 6 },
      { row: 1, seat: 7 },
      { row: 1, seat: 8 },
    ],
    [
      { row: 2, seat: 1 },
      { row: 2, seat: 2 },
      { row: 2, seat: 3 },
      { row: 2, seat: 4 },
      { row: 2 },
      { row: 2 },
      { row: 2, seat: 5 },
      { row: 2, seat: 6 },
      { row: 2, seat: 7 },
      { row: 2, seat: 8 },
    ],
    [
      { row: 3, seat: 1 },
      { row: 3, seat: 2 },
      { row: 3, seat: 3 },
      { row: 3, seat: 4 },
      { row: 3 },
      { row: 3 },
      { row: 3, seat: 5 },
      { row: 3, seat: 6 },
      { row: 3, seat: 7 },
      { row: 3, seat: 8 },
    ],
    [
      { row: 4, seat: 1 },
      { row: 4, seat: 2 },
      { row: 4, seat: 3 },
      { row: 4, seat: 4 },
      { row: 4 },
      { row: 4 },
      { row: 4, seat: 5 },
      { row: 4, seat: 6 },
      { row: 4, seat: 7 },
      { row: 4, seat: 8 },
    ],
    [
      { row: 5, seat: 1 },
      { row: 5, seat: 2 },
      { row: 5, seat: 3 },
      { row: 5, seat: 4 },
      { row: 5 },
      { row: 5 },
      { row: 5, seat: 5 },
      { row: 5, seat: 6 },
      { row: 5, seat: 7 },
      { row: 5, seat: 8 },
    ],
    [
      { row: 6, seat: 1 },
      { row: 6, seat: 2 },
      { row: 6, seat: 3 },
      { row: 6, seat: 4 },
      { row: 6 },
      { row: 6 },
      { row: 6, seat: 5 },
      { row: 6, seat: 6 },
      { row: 6, seat: 7 },
      { row: 6, seat: 8 },
    ],
  ],
};
